#=================================================================================
# Copyright (c) 2009, 2018 Robert Bosch GmbH and its subsidiaries.
# This program and the accompanying materials are made available under
# the terms of the Bosch Internal Open Source License v4
# which accompanies this distribution, and is available at
# http://bios.intranet.bosch.com/bioslv4.txt
#=================================================================================

#  n/a
parameters:
- name: ARTIFACTORY_URL
  type: string
  default: ''

stages:
- stage: push_artifactory
  displayName: Archive to Artifactory

  jobs:

  - job: pushing_to_artifactory
    steps:
    - script: |
        sudo apt-get update
        sudo apt-get install zip -y
        sudo apt-get install g++-aarch64-linux-gnu -y
        sudo apt-get install gcc-aarch64-linux-gnu -y
        sudo apt-get install cmake -y
      displayName: 'Install sofwares'
    
    - script: |
        echo BUILDING
        mkdir model_A_ver1_0__/api
        cd sdvapi/Debug
        make clean
        make all
        cd ../../FotaMaster/UdsClient/Debug
        make clean
        make all
        cd ../../../
        cp sdvapi/soahandler/data/* model_A_ver1_0__/gw || exit 1
        cp FotaMaster/UdsClient/Debug/libUdsClient.so model_A_ver1_0__/api || exit 1
        cp sdvapi/Debug/libsdvapi.so model_A_ver1_0__/api || exit 1
      displayName: 'Collect materials'

    - script: zip -r model_DevOpsTest1.zip model_A_ver1_0__
      displayName: 'ZIP FILE'

    - script: |
        set -exo pipefail
        jf config add jfrog-artifactory --url=https://artifactory.boschdevcloud.com/ --user=$(artifactory-write-user) --password=$(artifactory-write-user-key) --interactive=false --overwrite
        export UPLOAD_FOLDER="${{parameters.ARTIFACTORY_URL}}/$(Build.BuildId)"
        cd $(Build.Repository.LocalPath)
        jf rt upload --flat=false *.zip ${UPLOAD_FOLDER}/ --recursive=false
      displayName: 'Archive file to artifactory'
