#=================================================================================
# Copyright (c) 2009, 2018 Robert Bosch GmbH and its subsidiaries.
# This program and the accompanying materials are made available under
# the terms of the Bosch Internal Open Source License v4
# which accompanies this distribution, and is available at
# http://bios.intranet.bosch.com/bioslv4.txt
#=================================================================================

#  n/a
parameters:
- name: DOCKER_BUILD_ARG
  type: string
  default: ''

stages:
- stage: send_email
  displayName: Send email

  jobs:
  - job: send_email_confirm
    steps:
    - script: echo SEND_EMAIL
      displayName: 'SEND EMAIL'
