# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- ABCD

pr:
  branches:
    include:
    - ABCD
  paths:
    exclude: # file paths which will not trigger a build
    - README.md
    - .gitignore

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, ABCD Team!
  displayName: 'Just a friendly message'

- script: |
    sudo apt-get update -y
    sudo apt-get upgrade -y
  displayName: 'Upgrade system'

- script: |
    pip install pipreqs
    pipreqs --force
  displayName: 'Create requirements.txt'

- script: pip install -r requirements.txt -y
  displayName: 'Install requirements'

- script: pip install bandit safety pylint
  displayName: 'Install test unit'

- script: bandit -r .
  displayName: 'Test code vulnerability'

- script: safety check
  displayName: 'Test dependencies vulnerabilities'

- script: |
    pylint src/applications.py --errors-only
    pylint src/lib.py --errors-only
  displayName: 'Test syntax'

- script: python -m unittest discover tests
  displayName: 'Run tests'

- script: echo Done !!!
  displayName: 'Done testing'