# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Pull Request Triggers (triggers the pipeline whenever a pull request is opened with the specified target branches)
trigger: none

pr:
  branches:
    include:
    - main
  paths:
    exclude: # file paths which will not trigger a build
    - README.md
    - .gitignore

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
    echo Install dependency
    sudo apt-get install python3 python3-pip virtualenv -y
    wget https://github.com/github/codeql-action/releases/download/codeql-bundle-20230428/codeql-bundle-linux64.tar.gz
    tar -xvzf ./codeql-bundle-linux64.tar.gz
    export PATH=$PATH:$PWD/codeql

  displayName: 'Get latest CodeQL package. Install on Agent.'

- script: |
    echo Start Security Static Check
    ./codeql/codeql database create codeql-dbs --source-root=sontran --language=python
    ./codeql/codeql database analyze codeql-dbs python-code-scanning.qls \
    --format=csv --output=python-results.csv

  displayName: 'Run sec scanning'

- script: |
    cat python-results.csv

  displayName: 'Check result'
